### ISSUE TITLE
1Q9A should be parsed to see if SuiteName can handle alternate conformations

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Molprobity2#116]

**Comment by russell-taylor** [comment]
@Joymaker Please address and close this issue.

**Comment by Joymaker** [comment]
Depended upon fully solving the problem of computing dihedral angles from PDB files without the restraints manager.  Done.  Conformer A perfectly matches the output of the old C code.  (Conformer B could not be got through the old C code with tools in hand.)
