### ISSUE TITLE
Add a description of what SuiteName does to the top of the documentation

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Molprobity2#117]
Have Dave and Jane review the wording once it is ready.

**Comment by russell-taylor** [comment]
@Joymaker Go ahead and add the text that you sent to Dave and Jane as a triple-quotes string.  We'll change it once we hear back from them.

**Comment by Joymaker** [comment]
I got something back from Jane, but unfortunately she used non-ASCII characters that turned into gibberish in transmission. I have asked her to clarify and shortly we should have the real text in place.

Ken

On 7/22/2021 7:55:17 AM, Russell Taylor ***@***.***> wrote:
@Joymaker [https://github.com/Joymaker] Go ahead and add the text that you sent to Dave and Jane as a triple-quotes string. We'll change it once we hear back from them.
