### ISSUE TITLE
Consider selecting only the standard bases in protein and RNA and then doing restraints only on that subset

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Molprobity2#135]
Something like "drop hetatoms".  Only run restraints on that subset.

Then consider how to handle the "standard" modified bases.
- Most of the modified bases do not change the main chain, and those that do have extra atoms that could be ignored

Think about how to handle DNA in the future as an option: make sure it doesn't barf on normal DNA.

**Comment by russell-taylor** [comment]
Leave the DNA part for "if there is time" future work.

**Comment by Joymaker** [comment]
Have we superseded this? For Suitename at least, we don't need restraints at all anymore. Or is this actually relevant to Probe as well?

**Comment by russell-taylor** [comment]
This is superseded by https://github.com/ReliaSolve/Molprobity2/issues/142
