### ISSUE TITLE
Make a dihedral calculator that bases things on atom names within a residue

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Molprobity2#142]
Look for O2' and the proper atoms in RNA in any residue and claim that is an RNA

Do the conformers separately -- have it just pick one of them that matches the one asked for or the first one as it already does now.

We'll need to figure out what to do about multiple models.  As a first pass, it should read the first model in the file by default and have a command-line option to select a model.  We'll need to figure out what can happen with the output formats if multiple models are selected.

**Comment by Joymaker** [comment]
Okay, so I have a dihedral calculator that works from a limited set of atom names. Probably could be readily generalized to the purpose indicated here. Let's talk and flesh out what we need.

**Comment by russell-taylor** [comment]
This issue was intended to be the front end for the CCTBX SuiteName PDB reader, so the issue should be closed once you have it working for that purpose.  We don't need a general one for now.

We will want unit tests, of course, to ensure that it works for different orientations and any special cases.

**Comment by Joymaker** [comment]
Working, and handling partially-alt-conformer residues correctly.
