### ISSUE TITLE
Differences in 6hhq

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Molprobity2#155]
String outputs differ:

```
taylorr@reliasolve-3:~/src/suitename_regression/outputs$ diff 6hhq.string.orig 6hhq.string.new
0a1,3
> [' ', '1', 'sR', '1401', ' ', ' ', '  A']
> [  0.     80.668 233.092 273.915 295.102 155.065  63.718  85.561   0.   ]
> 1a
```

Report outputs differ with the same extra block of text in the new.

Kinemage also has the block of text in the new.

**Comment by Joymaker** [comment]
An obscure bear trap in the code that I thought I had closed. Sorry about that!
