### ISSUE TITLE
Complete and approve list of tools to include in the project scope

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Molprobity2#3]
Check the "Tools to include" section of the "Molprobity++ Planning" document to make sure all tools we are planning to port are listed.

**Comment by vbchen** [comment]
In my mind, reduce and probe are far and away the highest priorities, and suitename is good one for you to get started on.  Those three would benefit the most from your expertise.  Most of the other tools in that list probably do need some work, but there's overlapping responsibilities on most of those.  The kinemage viewing tools, for example, I feel like is my responsibility, and a lot of the existing cctbx versions of the tools Christopher has a pretty good handle on.  I do like the idea of keeping a comprehensive list of our tools that need work, but I don't know if that section is necessarily the right place for that list and your workflow.

**Comment by prisant** [comment]
Concur with VBC's summary comment. Michael

**Comment by russell-taylor** [comment]
Roger that, thanks!
