### ISSUE TITLE
Hydrogenate vs. reduce tests are not working for me on some input files

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Molprobity2#58]
3c3z_RNA_A-U-C-G-test_RIO-charge_test.pdb is one such file.

**Comment by russell-taylor** [comment]
Dorothee tried the above file on 1/13/2021 and it worked for her, so I need to rerun and see if it is now working or else try and see what is different between our environments.

**Comment by russell-taylor** [comment]
The current master version is looking for the elbow module, which comes with phenix.  We'll need to avoid using it or have it pulled into the open-source portion of cctbx to use it going forward.

**Comment by chrissciwilliams** [comment]
I believe that Elbow is one of the proprietary components of Phenix, so we
should avoid using it.  Nigel Moriarty at Berkeley is the person to talk to
about Elbow and whether there is an open-source version.

-Christopher Williams
---Richardson Lab, Duke University

**Comment by russell-taylor** [comment]
Asked Dorothee and Nigel whether there is an open-source alternative that we can use.

**Comment by russell-taylor** [comment]
When Dorothee fixed the above problem by moving the import, we are back to the original crash.

According to Nigel, this is a new dependency on the chem_data files that cannot be resolved using environment variables.  They are working on a solution.  In the meantime, I could try putting the chem_data from one of my repositories into the chem_data directory.

**Comment by russell-taylor** [comment]
Nigel and Dorothee are looking for a solution to this problem, which involves needing to specify any ligands from the chem_data dictionaries.  Until that is fixed, we'll only be able to run on files without such ligands.  Once we have it working, send Jane a run comparing the 3c3z file listed at the top of this issue.

**Comment by russell-taylor** [comment]
Copying the chem_data module from a Phenix build into a cctbx build lets us run on these files.

**Comment by russell-taylor** [comment]
As of today, 3c3z_half.pdb fails to run inside a Phenix build due to missing information on the residue UMS.
