### ISSUE TITLE
Ensure that SuiteName '-' command line argument lets it read from standard input

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Molprobity2#89]
Ken, please verify that this works and close this issue.

**Comment by Joymaker** [comment]
Suitename reads from the standard input without any such command line argument, as long as you do not give it a file name as the first argument. Is this isolated '-' argument a feature we want to add, anyway?

On 2/19/2021 9:47:05 AM, Russell Taylor <notifications@github.com> wrote:
Assigned #89 [https://github.com/ReliaSolve/Molprobity2/issues/89] to @Joymaker [https://github.com/Joymaker].

**Comment by russell-taylor** [comment]
Let's not add that -- it must be parsed by the wrapper code.  Thanks!
