### ISSUE TITLE
Change the SuiteName license to Apache2

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Molprobity2#96]

**Comment by russell-taylor** [comment]
See the "How to apply the apache license to your work" section of https://www.apache.org/licenses/LICENSE-2.0
Name of copyright owner is Richardson Lab at Duke University

Add the notice to all of the Python files and add a LICENSE text in the root directory.

**Comment by Joymaker** [comment]
Among the files required for CCTBX integration there are some in which the inclusion of Apache license text would make the license text far greater than the remaining content of the file. They are boilerplate, directly adapted from Phoenix and CCTBX standards, and contain absolutely no real intellectual property. Do we feel the need to put Apache comments even there, or can we save them for the files that really do the work?

**Comment by russell-taylor** [comment]
If there is a LICENSE text file in the root directory I think it is okay to not have this in the boilerplate files.

**Comment by russell-taylor** [comment]
At least one of the files has the copyright owner as David C. Richardson rather than Richardson Lab at Duke University

**Comment by russell-taylor** [comment]
At least the dualparse.py file has "Richardson Lab" rather than "Richardson Lab at Duke University".  Please change all of them to the proper name.
